project:
  type: website
  output-dir: docs

website:
  title: "Muhammad Yaseen"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - about.qmd
          
      

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

